### ISSUE TITLE
Precision testing

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/libm#147]
Part of the testing harness should be to test the worst case precision of the APIs. Probably, the easiest way to do this would be to use the `mpfr` library as a dev-dependency and use it to check that all APIs have a worst-case precision of 0.5 ULPs. For the APIs taking multiple `f32`s or `f64`s we can't feasibly test them for all inputs, but these should at least be exhaustively tested for the inputs that generally trigger the worst-case precision.

**Comment by tgross35** [comment]
Done, only took 6 years :) https://github.com/rust-lang/libm/pull/311
