### ISSUE TITLE
Unify different code paths via macro

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/libm#217]
Per https://github.com/rust-lang-nursery/libm/pull/216#pullrequestreview-272616682:

* We want a macro that allows us to cleanly implement various hardware optimized code paths depending on what intrinsics are available at compile time, while also having fallbacks for any platforms without the same hardware abilities.
* There's various code branches that could be involved here, so "something like" the `cfg_if!` macro is appropriate here. A macro that's general to several possible situations.
* That macro _could_ literally be `cfg_if!`, but that adds in a dependency to a very low level crate. If we can come up with something focused to our particular case that's kept here in this tree that would probably be preferred.
* There is also the `llvm_intrinisically_optimized!` macro, which perhaps we could just extend some more, depending on how folks feel about that.

**Comment by tgross35** [comment]
We have a macro for this now https://github.com/rust-lang/libm/blob/d9bfeca91b8aebc628b0e5108ce31b3809014b7f/src/math/support/macros.rs#L42-L70. Architecture-specific functions and intrinsics go in https://github.com/rust-lang/libm/tree/d9bfeca91b8aebc628b0e5108ce31b3809014b7f/src/math/arch, you just tell the macro when you want to use them https://github.com/rust-lang/libm/blob/d9bfeca91b8aebc628b0e5108ce31b3809014b7f/src/math/sqrt.rs#L84-L89.
