### ISSUE TITLE
Publish a version with the `sincosf` fix

### ISSUE THREAD

**Issue by nical** [rust-lang/libm#231]
We are eager to use a version of libm with the `sincosf` fix from #229 in [euclid](https://github.com/servo/euclid).

It would be great to get the fix published on crates.io. Either `0.2.0` which is what master has in Cargo.toml, or if the `0.2.0` is pending on upcoming work in progress, creating a `0.1.5` branch on top of `0.1.4` with a backport of the fix would work just as well.

**Comment by CryZe** [comment]
I don't think 0.2.0 would work out, as num-traits already depends on 0.1, so num-traits would have to upgrade to 0.2, which is a breaking change for them, which is probably not going to happen anytime soon.

**Comment by alexcrichton** [comment]
@nical given the recent comment do you still need a new release?

**Comment by CryZe** [comment]
Well a release is still needed, it just should likely be 0.1.x again. Although I don't think 0.2 is actually a breaking change for num-traits, so num-traits could also just release a new version.

**Comment by nical** [comment]
@alexcrichton yes, because the sincosf fix is important (in my humble opinion). The release could gbe either a `0.2.x` release or via a `0.1.x` branch, both work for me (although as @CryZe said I suspect that having a `0.1.x` branch without the removal of Float32Ext and Float64Ext  would be the path of least disturbance for the ecosystem of crates that depend on libm in general).

**Comment by alexcrichton** [comment]
Ok, I've published 0.2.0

**Comment by nical** [comment]
Thanks!
