### ISSUE TITLE
aarch 64 compilation failure. 

### ISSUE THREAD

**Issue by leccyworld** [rust-lang/libm#256]
Trying to build libm as part of opendp  for aarch64 target. 
Its failing with below error
>>note: cc: error: unrecognized command line option '-m64'
Seems its still trying to use X86 flags,  Isthis librsry not supported on aarch64 platforms at all?

**Comment by Amanieu** [comment]
This crate compiles fine on aarch64 for me:
```
cargo build --target aarch64-unknown-linux-gnu
    Updating crates.io index
   Compiling libm v0.2.1 (/home/amanieu/code/compiler-builtins/libm)
    Finished dev [unoptimized + debuginfo] target(s) in 4.30s
```
Did you set up your aarch64 cross-compiler correctly in `~/.cargo/config`?

```
[target.aarch64-unknown-linux-gnu]
ar = "aarch64-linux-gnu-ar"
linker = "aarch64-linux-gnu-gcc"
```

**Comment by leccyworld** [comment]
I have that in config. Do you have gcc  installed on your system? I didnt have gcc on my VM initially. After installing gcc it seems to compile with the target=aarch64 command.

**Comment by tgross35** [comment]
It sounds like this was resolved, so I will close this.
