### ISSUE TITLE
Using rint/rintf instead of roundeven/roundevenf appears to break target_arch = "spirv" for spirv-std  

### ISSUE THREAD

**Issue by charles-r-earp** [rust-lang/libm#273]
Commit 7c02ee9f5130cdf3401a5b4452836731c8b047e6 in 0.2.6 likely causes https://github.com/EmbarkStudios/rust-gpu/issues/938.

**Comment by Amanieu** [comment]
This should be fixed in rust-gpu by handling the new functions here: https://github.com/EmbarkStudios/rust-gpu/blob/main/crates/rustc_codegen_spirv/src/builder/libm_intrinsics.rs
