### ISSUE TITLE
specify MSRV

### ISSUE THREAD

**Issue by joseluis** [rust-lang/libm#279]
Currenly only the edition `2018` is specified, which implicitly sets the MSRV to `1.31.0`, but libm doesn't compile with that version.

The first compatble rust version is `1.43.0`, when the associated EPSILON constant was stabilized, which is used in the rint / rintf modules.

And it also fixes another compilation error while trying to load the limb_helper module.

**Comment by tgross35** [comment]
https://github.com/rust-lang/libm/pull/332 set the MSRV to 1.63, which is Debian stable. I don't know how long we will stick with this version, but it won't be bumped unless there is a specific feature we would like to make use of.
