### ISSUE TITLE
Licensing issues?

### ISSUE THREAD

**Issue by porglezomp** [rust-lang/libm#73]
The musl libc implementations include lines like the following:
```c
/* origin: FreeBSD /usr/src/lib/msun/src/k_cos.c */
/*
 * ====================================================
 * Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.
 *
 * Developed at SunSoft, a Sun Microsystems, Inc. business.
 * Permission to use, copy, modify, and distribute this
 * software is freely granted, provided that this notice
 * is preserved.
 * ====================================================
 */
```
Should these remain present in the ported versions, given that these seem to me like a derived work?

**Comment by japaric** [comment]
IANAL but we probably want to keep the license headers and also have a [COPYRIGHT file MUSL does][musl-copyright]. I'm not sure though -- [compiler-builtins], a Rust port of compiler-rt, doesn't keep the license headers (but those are more homogeneous); it just contains a copy of [compiler-rt license].

[musl-copyright]: https://git.musl-libc.org/cgit/musl/tree/COPYRIGHT#n105
[compiler-builtins]: https://github.com/rust-lang-nursery/compiler-builtins/
[compiler-rt license]: https://github.com/rust-lang-nursery/compiler-builtins/blob/master/LICENSE.TXT

@alexcrichton @steveklabnik assuming this will end up as a submodule of rust-lang/rust what should we do wrt to licensing and copyright notices?

**Comment by steveklabnik** [comment]
As far as I know, headers are unnneccesary. They’re still in the tree for legacy reasons but new code doesn’t use them. I think? At least, none of the crates we pull in do; are you planning a submodule for sure? Why not a regular crate?

**Comment by porglezomp** [comment]
Just to clarify since I'm not sure which of these you mean Steve: we're asking about the Sun Microsystems headers that were already in the MUSL code that's being ported, not Rust license headers.

**Comment by steveklabnik** [comment]
Ah! Yes I was confused. Ignore my previous post.

**Comment by japaric** [comment]
> are you planning a submodule for sure? Why not a regular crate?

Some of the math code may end in core (which can't depend on any crate); the rest will go into compiler-builtins (which can only depend on core). The code will be source imported (`#[path = ..] mod libm`); due to these constraints and that requires a submodule.

**Comment by alexcrichton** [comment]
Unfortunately I have little knowledge about what this means, I don't know what we need to do in terms of licensing :(

**Comment by japaric** [comment]
For the time being all the copyright notices / headers in C files have been copied over to the Rust files. I don't know if we need anything else though.

**Comment by tgross35** [comment]
Licensing was updated in https://github.com/rust-lang/libm/pull/317. Summary:
- This library is available for use under the MIT license, since that is what most source is derived from (musl)
- Non-derivative contributions to this library are MIT OR Apache-2.0
- We do need to retain copyright headers from any source files
